### PR TITLE
Update certificate parsing for certificate chains with multiple certificates

### PR DESCRIPTION
**Pull request by jakul**
Fix for https://github.com/carlnordenfelt/aws-api-gateway-for-cloudformation/issues/49.

Update the certificate parsing so that it works when certificate chains have multiple certificates within them.

@carlnordenfelt Can you review & merge please?

### CODE REVIEW

**Comment by carlnordenfelt** [comment]
Hi,

I'll take a look at the PR as soon as I get back to civilization which is
on thursday.

**Comment by carlnordenfelt** [comment]
I've merged but won't be able to  relate a new package until tomorrow. In the meantime you can create your own package and deploy if you want.

**Comment by carlnordenfelt** [comment]
2.0.1 has been released with the fix.

**Comment by jakul** [comment]
Cheers!

Em qui, 21 de jul de 2016 17:21, Carl Nordenfelt <notifications@github.com>
escreveu:

**Pull request merged**
